apiVersion: v1
kind: Secret
metadata:
  name: sentinelmesh-db-secret
  namespace: sentinelmesh
type: Opaque
stringData:
  DB_HOST: "postgresql.database.svc.cluster.local"
  DB_USER: "sentinel"
  DB_PASSWORD: "password"
  DB_NAME: "sentinelmesh"
  DB_PORT: "5432"
