// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: incidents.proto

package incidents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIncidentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceId     string                 `protobuf:"bytes,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"` // optional
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                        // optional, e.g., "ACTIVE", "RESOLVED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentsRequest) Reset() {
	*x = GetIncidentsRequest{}
	mi := &file_incidents_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentsRequest) ProtoMessage() {}

func (x *GetIncidentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentsRequest.ProtoReflect.Descriptor instead.
func (*GetIncidentsRequest) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{0}
}

func (x *GetIncidentsRequest) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *GetIncidentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Incident struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceId     string                 `protobuf:"bytes,2,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ResolvedAt    int64                  `protobuf:"varint,7,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	Severity      string                 `protobuf:"bytes,8,opt,name=severity,proto3" json:"severity,omitempty"` // P1, P2, P3
	AckedAt       int64                  `protobuf:"varint,9,opt,name=acked_at,json=ackedAt,proto3" json:"acked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Incident) Reset() {
	*x = Incident{}
	mi := &file_incidents_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Incident) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Incident) ProtoMessage() {}

func (x *Incident) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Incident.ProtoReflect.Descriptor instead.
func (*Incident) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{1}
}

func (x *Incident) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Incident) GetServiceId() string {
	if x != nil {
		return x.ServiceId
	}
	return ""
}

func (x *Incident) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Incident) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Incident) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Incident) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Incident) GetResolvedAt() int64 {
	if x != nil {
		return x.ResolvedAt
	}
	return 0
}

func (x *Incident) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Incident) GetAckedAt() int64 {
	if x != nil {
		return x.AckedAt
	}
	return 0
}

type GetIncidentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incidents     []*Incident            `protobuf:"bytes,1,rep,name=incidents,proto3" json:"incidents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIncidentsResponse) Reset() {
	*x = GetIncidentsResponse{}
	mi := &file_incidents_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIncidentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIncidentsResponse) ProtoMessage() {}

func (x *GetIncidentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIncidentsResponse.ProtoReflect.Descriptor instead.
func (*GetIncidentsResponse) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{2}
}

func (x *GetIncidentsResponse) GetIncidents() []*Incident {
	if x != nil {
		return x.Incidents
	}
	return nil
}

type UpdateIncidentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IncidentId    string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentStatusRequest) Reset() {
	*x = UpdateIncidentStatusRequest{}
	mi := &file_incidents_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentStatusRequest) ProtoMessage() {}

func (x *UpdateIncidentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateIncidentStatusRequest) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateIncidentStatusRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *UpdateIncidentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateIncidentStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Incident      *Incident              `protobuf:"bytes,2,opt,name=incident,proto3" json:"incident,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIncidentStatusResponse) Reset() {
	*x = UpdateIncidentStatusResponse{}
	mi := &file_incidents_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIncidentStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIncidentStatusResponse) ProtoMessage() {}

func (x *UpdateIncidentStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_incidents_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIncidentStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateIncidentStatusResponse) Descriptor() ([]byte, []int) {
	return file_incidents_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateIncidentStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateIncidentStatusResponse) GetIncident() *Incident {
	if x != nil {
		return x.Incident
	}
	return nil
}

var File_incidents_proto protoreflect.FileDescriptor

const file_incidents_proto_rawDesc = "" +
	"\n" +
	"\x0fincidents.proto\x12\tincidents\"L\n" +
	"\x13GetIncidentsRequest\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\tR\tserviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x80\x02\n" +
	"\bIncident\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"service_id\x18\x02 \x01(\tR\tserviceId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1f\n" +
	"\vresolved_at\x18\a \x01(\x03R\n" +
	"resolvedAt\x12\x1a\n" +
	"\bseverity\x18\b \x01(\tR\bseverity\x12\x19\n" +
	"\backed_at\x18\t \x01(\x03R\aackedAt\"I\n" +
	"\x14GetIncidentsResponse\x121\n" +
	"\tincidents\x18\x01 \x03(\v2\x13.incidents.IncidentR\tincidents\"V\n" +
	"\x1bUpdateIncidentStatusRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"i\n" +
	"\x1cUpdateIncidentStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12/\n" +
	"\bincident\x18\x02 \x01(\v2\x13.incidents.IncidentR\bincident2\xcb\x01\n" +
	"\x0fIncidentService\x12O\n" +
	"\fGetIncidents\x12\x1e.incidents.GetIncidentsRequest\x1a\x1f.incidents.GetIncidentsResponse\x12g\n" +
	"\x14UpdateIncidentStatus\x12&.incidents.UpdateIncidentStatusRequest\x1a'.incidents.UpdateIncidentStatusResponseB4Z2github.com/ykadam006/sentinelmesh/protos/incidentsb\x06proto3"

var (
	file_incidents_proto_rawDescOnce sync.Once
	file_incidents_proto_rawDescData []byte
)

func file_incidents_proto_rawDescGZIP() []byte {
	file_incidents_proto_rawDescOnce.Do(func() {
		file_incidents_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_incidents_proto_rawDesc), len(file_incidents_proto_rawDesc)))
	})
	return file_incidents_proto_rawDescData
}

var file_incidents_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_incidents_proto_goTypes = []any{
	(*GetIncidentsRequest)(nil),          // 0: incidents.GetIncidentsRequest
	(*Incident)(nil),                     // 1: incidents.Incident
	(*GetIncidentsResponse)(nil),         // 2: incidents.GetIncidentsResponse
	(*UpdateIncidentStatusRequest)(nil),  // 3: incidents.UpdateIncidentStatusRequest
	(*UpdateIncidentStatusResponse)(nil), // 4: incidents.UpdateIncidentStatusResponse
}
var file_incidents_proto_depIdxs = []int32{
	1, // 0: incidents.GetIncidentsResponse.incidents:type_name -> incidents.Incident
	1, // 1: incidents.UpdateIncidentStatusResponse.incident:type_name -> incidents.Incident
	0, // 2: incidents.IncidentService.GetIncidents:input_type -> incidents.GetIncidentsRequest
	3, // 3: incidents.IncidentService.UpdateIncidentStatus:input_type -> incidents.UpdateIncidentStatusRequest
	2, // 4: incidents.IncidentService.GetIncidents:output_type -> incidents.GetIncidentsResponse
	4, // 5: incidents.IncidentService.UpdateIncidentStatus:output_type -> incidents.UpdateIncidentStatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_incidents_proto_init() }
func file_incidents_proto_init() {
	if File_incidents_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_incidents_proto_rawDesc), len(file_incidents_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_incidents_proto_goTypes,
		DependencyIndexes: file_incidents_proto_depIdxs,
		MessageInfos:      file_incidents_proto_msgTypes,
	}.Build()
	File_incidents_proto = out.File
	file_incidents_proto_goTypes = nil
	file_incidents_proto_depIdxs = nil
}
